// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebTT.Entities;

#nullable disable

namespace WebTT.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    [Migration("20230713095008_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebTT.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("NameTk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("WebTT.Entities.chuas", b =>
                {
                    b.Property<int>("chuaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chuaid"));

                    b.Property<DateTime?>("capnhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ngaythanhlap")
                        .HasColumnType("datetime2");

                    b.Property<string>("tenchua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trutri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("chuaid");

                    b.ToTable("chuas");
                });

            modelBuilder.Entity("WebTT.Entities.daotrangs", b =>
                {
                    b.Property<int>("daotrangid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("daotrangid"));

                    b.Property<bool?>("daketthuc")
                        .HasColumnType("bit");

                    b.Property<int?>("nguoitrutri")
                        .HasColumnType("int");

                    b.Property<string>("noidung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noitochuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sothanhvienthamgia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("thoigiantochuc")
                        .HasColumnType("datetime2");

                    b.HasKey("daotrangid");

                    b.ToTable("daotrangs");
                });

            modelBuilder.Entity("WebTT.Entities.dondangkys", b =>
                {
                    b.Property<int>("dondangkyid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dondangkyid"));

                    b.Property<int?>("daotrangid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ngayguidon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngayxuly")
                        .HasColumnType("datetime2");

                    b.Property<int?>("nguoixuly")
                        .HasColumnType("int");

                    b.Property<int?>("phattuid")
                        .HasColumnType("int");

                    b.Property<int?>("phatuid")
                        .HasColumnType("int");

                    b.Property<int?>("trangthaidon")
                        .HasColumnType("int");

                    b.HasKey("dondangkyid");

                    b.HasIndex("daotrangid");

                    b.HasIndex("phattuid");

                    b.ToTable("dondangkys");
                });

            modelBuilder.Entity("WebTT.Entities.kieuthanhviens", b =>
                {
                    b.Property<int>("kieuthanhvienid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kieuthanhvienid"));

                    b.Property<string>("code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenkieu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kieuthanhvienid");

                    b.ToTable("kieuthanhviens");
                });

            modelBuilder.Entity("WebTT.Entities.phattu", b =>
                {
                    b.Property<int>("phattuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("phattuid"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("anhchup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("chuaid")
                        .HasColumnType("int");

                    b.Property<bool?>("dahoantuc")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("gioitinh")
                        .HasColumnType("int");

                    b.Property<string>("ho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("kieuthanhvienid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngayhoantuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ngayxuatgia")
                        .HasColumnType("datetime2");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phapdanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ten")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tendem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("phattuid");

                    b.HasIndex("AdminId");

                    b.HasIndex("chuaid");

                    b.HasIndex("kieuthanhvienid");

                    b.ToTable("phattus");
                });

            modelBuilder.Entity("WebTT.Entities.phattudaotrangs", b =>
                {
                    b.Property<int>("phattudaotrangid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("phattudaotrangid"));

                    b.Property<int?>("daotrangid")
                        .HasColumnType("int");

                    b.Property<bool?>("dathamgia")
                        .HasColumnType("bit");

                    b.Property<string>("lydokhongthamgia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("phattuid")
                        .HasColumnType("int");

                    b.HasKey("phattudaotrangid");

                    b.HasIndex("daotrangid");

                    b.HasIndex("phattuid");

                    b.ToTable("phattudaotrangs");
                });

            modelBuilder.Entity("WebTT.Entities.token", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool?>("expired")
                        .HasColumnType("bit");

                    b.Property<int?>("phattuid")
                        .HasColumnType("int");

                    b.Property<bool?>("revoked")
                        .HasColumnType("bit");

                    b.Property<string>("stoken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("token_type")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("phattuid");

                    b.ToTable("token");
                });

            modelBuilder.Entity("WebTT.Entities.dondangkys", b =>
                {
                    b.HasOne("WebTT.Entities.daotrangs", "daotrang")
                        .WithMany("dondangkys")
                        .HasForeignKey("daotrangid");

                    b.HasOne("WebTT.Entities.phattu", "phattu")
                        .WithMany()
                        .HasForeignKey("phattuid");

                    b.Navigation("daotrang");

                    b.Navigation("phattu");
                });

            modelBuilder.Entity("WebTT.Entities.phattu", b =>
                {
                    b.HasOne("WebTT.Entities.Admin", "Admin")
                        .WithMany("phattus")
                        .HasForeignKey("AdminId");

                    b.HasOne("WebTT.Entities.chuas", "chua")
                        .WithMany("phattu")
                        .HasForeignKey("chuaid");

                    b.HasOne("WebTT.Entities.kieuthanhviens", "kieuthanhvien")
                        .WithMany("phattu")
                        .HasForeignKey("kieuthanhvienid");

                    b.Navigation("Admin");

                    b.Navigation("chua");

                    b.Navigation("kieuthanhvien");
                });

            modelBuilder.Entity("WebTT.Entities.phattudaotrangs", b =>
                {
                    b.HasOne("WebTT.Entities.daotrangs", "daotrang")
                        .WithMany("phattudaotrangs")
                        .HasForeignKey("daotrangid");

                    b.HasOne("WebTT.Entities.phattu", "phattu")
                        .WithMany("phattudaotrangs")
                        .HasForeignKey("phattuid");

                    b.Navigation("daotrang");

                    b.Navigation("phattu");
                });

            modelBuilder.Entity("WebTT.Entities.token", b =>
                {
                    b.HasOne("WebTT.Entities.phattu", "phattu")
                        .WithMany("tokens")
                        .HasForeignKey("phattuid");

                    b.Navigation("phattu");
                });

            modelBuilder.Entity("WebTT.Entities.Admin", b =>
                {
                    b.Navigation("phattus");
                });

            modelBuilder.Entity("WebTT.Entities.chuas", b =>
                {
                    b.Navigation("phattu");
                });

            modelBuilder.Entity("WebTT.Entities.daotrangs", b =>
                {
                    b.Navigation("dondangkys");

                    b.Navigation("phattudaotrangs");
                });

            modelBuilder.Entity("WebTT.Entities.kieuthanhviens", b =>
                {
                    b.Navigation("phattu");
                });

            modelBuilder.Entity("WebTT.Entities.phattu", b =>
                {
                    b.Navigation("phattudaotrangs");

                    b.Navigation("tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
